### PR TITLE
Import SnabbVMX top

### PR DESCRIPTION
**Pull request by dpino**
Import Marcel's snabbvmx top command and adapt it to lwaftr branch.

The PR also fixes an error in ingress-packet-monitor timer. When checking whether the ingress-packet-drops counters exists is necessary to append the suffix ".counter" if not present. Otherwise there might be two counters:  "ingress-packet-drops" and "ingress-packet-drops.counter".

### CODE REVIEW

**Comment by mwiget** [comment]
Some counter names are chopped off. Maybe worth making column 1 a bit larger.

I did build it with this pull request, so should have everything in so far.
But great to see this familiar screen again after a long time ;-)

```
 lwaftr (rx/tx/txdrop in Mpps)   rx      tx      rxGb    txGb    txdrop
 lwaftr_v6                       0.05    0.05    0.16    0.16    0.049979
 lwaftr_v4                       0.05    0.00    0.14    0.00    0.000000

                                               Total           per second
 lwaftr_v6 in-ipv6-packets                   597,946               50,028
 lwaftr_v6 in-ipv6-bytes                 235,035,482           19,665,552
 lwaftr_v6 out-ipv6-packets                  597,948               50,028
 lwaftr_v6 out-ipv6-bytes                235,035,718           19,665,552
 lwaftr_v6 drop-all-ipv6-iface-              597,946               50,028
 lwaftr_v6 in-ipv6-frag-reassem                    0                    0
 lwaftr_v6 drop-ipv6-frag-inval                    0                    0
 lwaftr_v6 out-ipv6-frag                           0                    0
 lwaftr_v6 out-ipv6-frag-not                       0                    0

                                               Total           per second
 nic ifInDiscards                                  0                    0

                                               Total           per second
 lwaftr_v4 in-ipv4-packets                   597,948               50,028
 lwaftr_v4 in-ipv4-bytes                 211,117,798           17,664,432
 lwaftr_v4 out-ipv4-packets                        0                    0
 lwaftr_v4 out-ipv4-bytes                          0                    0
 lwaftr_v4 drop-all-ipv4-iface-                    0                    0
 lwaftr_v4 in-ipv4-frag-reassem                    0                    0
 lwaftr_v4 drop-ipv4-frag-inval                    0                    0
 lwaftr_v4 out-ipv4-frag                           0                    0
 lwaftr_v4 out-ipv4-frag-not                       0                    0
```

**Comment by dpino** [comment]
Fixed column adjustment and allow selecting snabb instance per id.

**Comment by kbara** [comment]
Overall, really nice work. On the nits side, luacheck is a bit loud about top.lua and it would be good to reduce the amount of output it has:

```
% luacheck top.lua 
Checking top.lua                                  Failure

    top.lua:3:7: unused variable S
    top.lua:32:4: accessing undefined variable main
    top.lua:69:28: unused argument code
    top.lua:71:4: accessing undefined variable main
    top.lua:84:10: setting non-standard global variable run
    top.lua:87:21: accessing undefined variable open_counters
    top.lua:88:10: unused variable configs
    top.lua:92:25: accessing undefined variable get_stats
    top.lua:96:10: accessing undefined variable print_lwaftr_metrics
    top.lua:105:10: setting non-standard global variable open_counters
    top.lua:124:10: setting non-standard global variable get_stats
    top.lua:141:10: setting non-standard global variable print_lwaftr_metrics
    top.lua:162:4: accessing undefined variable print_row
    top.lua:165:10: unused variable rx
    top.lua:165:14: unused variable tx
    top.lua:165:18: unused variable rxbytes
    top.lua:165:27: unused variable txbytes
    top.lua:165:36: unused variable drop
    top.lua:166:20: unused loop variable lwaftr
    top.lua:171:16: shadowing definition of variable rx on line 165
    top.lua:171:20: shadowing definition of variable tx on line 165
    top.lua:171:24: shadowing definition of variable rxbytes on line 165
    top.lua:171:33: shadowing definition of variable txbytes on line 165
    top.lua:171:42: shadowing definition of variable drop on line 165
    top.lua:177:10: accessing undefined variable print_row
    top.lua:178:13: accessing undefined variable float_s
    top.lua:179:13: accessing undefined variable float_s
    top.lua:180:13: accessing undefined variable float_s
    top.lua:181:13: accessing undefined variable float_s
    top.lua:182:13: accessing undefined variable float_l
    top.lua:189:20: unused loop variable lwaftr
    top.lua:197:13: accessing undefined variable print_row
    top.lua:198:16: accessing undefined variable int_s
    top.lua:198:32: accessing undefined variable int_s
    top.lua:202:16: accessing undefined variable print_row
    top.lua:203:19: accessing undefined variable int_s
    top.lua:203:35: accessing undefined variable int_s
    top.lua:210:10: setting non-standard global variable pad_str
    top.lua:215:10: setting non-standard global variable print_row
    top.lua:217:31: accessing undefined variable pad_str
    top.lua:222:10: setting non-standard global variable int_s
    top.lua:227:10: setting non-standard global variable float_s
    top.lua:231:10: setting non-standard global variable float_l
```

**Comment by dpino** [comment]
Updated top.lua. After clean up:

```
$ luacheck program/snabbvmx/top/top.lua 
Checking program/snabbvmx/top/top.lua             4 warnings

    program/snabbvmx/top/top.lua:1:1: accessing undefined variable module
    program/snabbvmx/top/top.lua:31:4: accessing undefined variable main
    program/snabbvmx/top/top.lua:199:4: accessing undefined variable main
    program/snabbvmx/top/top.lua:212:10: setting non-standard global variable run
```

**Comment by kbara** [comment]
LGTM

**Pull request merged**
