### PR TITLE
Add --ring-buffer-size option to --run

### PR DESCRIPTION
**Pull request by wingo**
Also fix -vv and remove documentation for -u.

### CODE REVIEW

**Comment by kbara** [comment]
I really like the patch. I'm uneasy about the lack of testing; I expect rarely-used options will break again. Could you add a shell script that runs this front-end with all the options that can be reasonably run without hardware and dies if they fail, and have that get run by 'make test', perhaps via our selftest.sh or a similar mechanism?

**Comment by dpino** [comment]
LGTM.

**Comment by wingo** [comment]
This front-end only runs with hardware, so there is no obvious test.

**Comment by kbara** [comment]
We need a script that runs a bunch of tests that require hardware, on hardware. Even if it's not run by normal CI, it could be part of the release process (although not a seamless one, given distro considerations).

**Comment by wingo** [comment]
@kbara ACK; i'll file an issue, in the future with tasks like that please file an issue directly :)

**Pull request merged**
