### PR TITLE
Add CHANGELOG

### PR DESCRIPTION
**Pull request by dpino**
Follows format of http://keepachangelog.com/

### CODE REVIEW

**Comment by dpino** [comment]
This PR solves #83.

**Comment by aperezdc** [comment]
LGTM.

**Comment by kbara** [comment]
It's not perfect, but let's merge it, and update it for 1.1. A mediocre changelog is better than no changelog.

**Comment by kbara** [comment]
@dpino are you willing to do the updating it for 1.1?

**Pull request merged**
