### PR TITLE
Binding table should only store information about PSID

### PR DESCRIPTION
**Pull request by dpino**
Implements #190

### CODE REVIEW

**Comment by andywingo** [comment]
I have a local change that does something like this.  Thinking about it more though, I think it's the wrong idea.  The reason is that the address map, the binding table, and also the side table of ipv6 addresses for the lwaftr are all logically part of the same thing -- as in, you can't interpret the binding table without the other two parts.  So really you want to compile them all together, so that the compiled binding table is sure to reference the address map and br table that it corresponds to.  (As it is, if we compiled the binding table to a podhashmap, we would be missing information for which lwaftr addess corresponds to each softwire.)

So really these should all be in the same file.  I propose:

```
ipv4_addresses {
  1.2.3.4 { psid_length=10 }
  5.6.7.8-5.6.7.255 { psid_length=4, shift=1 }
  ...
}

ipv6_addresses {
  8:9:a:b:c:d:e:f
  ...
}

softwires {
   { ipv4=178.79.150.233, psid=80, b4=127:2:3:4:5:6:7:128, aftr=0 }
   ...
}
```

The "aftr" field in a softwire would indicate the index of the address in ipv6_addresses, which would parse to an array.  Then the whole thing would get compiled to one file with one header, magic value, and recorded mtimes, and the file would have separate parts for the serialized range map, the serialized br array, and the serialized binding table.  Loading it via bt.load() would return three values as well -- or would it?  Maybe better to have one "binding table" object that has three parts internally but presents one interface to the world?  Dunno.  We will have to refactor other parts of the lwaftr so we will see.

WDYT diego?

**Comment by dpino** [comment]
@anywingo: I like the idea of having everything in one place because that's more consistent with the idea of having some sort of feature that allows to dump the binding table, where the binding table would be represented by the port ranges and softwire datasets.

I'm confused about the meaning of the `ipv6_addresses` array, do these values represent the B4 values or the bridges? It seems to me they represent IPv6 bridges, right? Adding a level of indirection makes everything harder to read IMHO. What would be the benefit of having these values stored in their own array? I think writing them down directly in the softwire entries would make be simpler.

About the binding table API, I prefer to expose one single interface, although internally information is stored in different datasets. FWIW, I like the current implementation:

```lua
local psid = lwstate.psid_info_map:lookup_psid(host_endian_ipv4, port)
for i=1,#lwstate.binding_table do
  -- Lookup entry
  local bind = lwstate.binding_table[i]
  if bind[2] == ipv4_ip then
     if bind[3] == psid then
        local lwaftr_ipv6 = get_lwAFTR_ipv6(lwstate, bind)
        return bind[1], lwaftr_ipv6
     end
  end
end
```

Maybe it could be turned into something like:

```lua
local psid = lwstate.bt:lookup_psid(host_endian_ipv4, port)
for i=1,#lwstate.bt.entries do
  local bind = lwstate.bt.entries[i]
  ...
end
```

**Comment by andywingo** [comment]
The ipv6_addresses is to specify the ipv6 address of the lwaftr.  There will be few of these.  Most b4's will probably be associated with a "main" aftr, and just some with additional addresses.  Since we won't be able to store the full IPv6 address in the compiled binding table (whose types you removed in this patch; why?), I thought it could make sense to also specify this set as a separate array.  Dunno.

Regarding lookup, the O(n) loop is not the api we need :)

**Comment by dpino** [comment]
Implemented by #193

**Pull request closed without merging**
