### PR TITLE
Added a regression test for end-addr

### PR DESCRIPTION
**Pull request by kbara**
This test checks that all softwires within a range specified with end-addr
actually work. Solves https://github.com/Igalia/snabb/issues/723 .

### CODE REVIEW

**Comment by kbara** [comment]
The test failure seems spurious - it's snabbvmx-related.

**Comment by dpino** [comment]
According to the CI output the error is in soaktest, not snabbvmx:

```
TEST      program/lwaftr/tests/soaktest/selftest.sh
ERROR     testlog/program.lwaftr.tests.soaktest.selftest.sh
```

**Comment by kbara** [comment]
I was looking at the snabb-2 result. You're right that the snabb-1 result was in soaktest.

**Comment by kbara** [comment]
@dpino the snabb-1 failure was legitimate - I hadn't done a vlan version of the test. I've fixed that, and it passes now.

**Review by dpino — APPROVED** [review]

**Pull request merged**
