### PR TITLE
Reduce 'snabb-lwaftr check' running time

### PR DESCRIPTION
**Pull request by dpino**
This PR solves #167.

### CODE REVIEW

**Comment by kbara** [comment]
LGTM, thanks.

**Comment by aperezdc** [comment]
The way I understand this is that the Snabb engine is run for a tenth of a second (0.1s), so if one runs the test suite in a slow machine (or a machine which is loaded) then the tests would not pass. I don't have a better idea right now to do this better, so the patch LGTM.

I will share a though here, in case it serves as inspiration: reading through the code, I noticed the `PcapReader` will stop sending data at the end of the input file (and set its `.done` attribute to `true`), so it is possible to detect when the input is exhausted. A different story is how to determine that all the expected output is produced — that's the tricky part. We will still want timeout (max duration?) to avoid that tests run forever. We may be able to do something by passing a “done” callback to `engine.main()` (relevant [code in app.lua](https://github.com/Igalia/snabbswitch/blob/master/src/core/app.lua#L227)).

**Comment by kbara** [comment]
@aperezdc sure, timeouts are -always- the wrong way to do this kind of test. We're not going to be running this on slow machines, and it's only worth optimizing doing it cleanly so much. If you have a burning desire to explore the pcap .done approach, go for it; otherwise, we have a **lot** of other things which could use the time and attention even more strongly.

**Comment by aperezdc** [comment]
@kbara: Dunno, I might look into it at some point. Anyway, as already said: this PR LGTM, so please merge it :ship:

**Comment by dpino** [comment]
I think this approach makes only sense for PCAP files. It's the only case I can think of where there's a limited amount of data that is pushed to a card. If the source of information is other thing different than a PCAP file, can never tell when traffic has ended. Modifying the engine to adapt to this particular case, it doesn't seem like a good idea to me, but that's my point of view. In essence, I agree with @kbara's comment.

**Comment by kbara** [comment]
Ok; let's merge it, with the idea we'll revert if it causes spurious test problems on -any- machine we routinely use, or try an intermediate value like 0.5.

**Comment by aperezdc** [comment]
@dpino: I think it can be done without modifying the engine, by providing a completion callback and making the “this test finished” check inside it. If needed, we could go to the point of monkey-patching things for testing, but I would rather avoid that if possible.

**Pull request merged**
