### PR TITLE
Reverted moving the wire-oriented counters to the edges

### PR DESCRIPTION
**Pull request by kbara**
This comes with a tradeoff: the overall incoming/outgoing counters are less
accurate (ie, 3 fragmented packets are counted as one incoming packet, of
less total bytes), but allows more freedom in app network configuration
(for instance, not using the fragmentation/reassembly apps).

### CODE REVIEW

**Comment by mwiget** [comment]
I don't see this as less accurate: lwaftr app works on completed packets, not fragments. The app receiving the packets from the wire has counters too and they count individual fragments.

**Comment by teknico** [comment]
LGTM

**Comment by kbara** [comment]
Well - it's specifically in terms of the lwaftr app, rather than the whole app network. So, for instance, in a configuration with fragmentation/reassembly apps, those will report that they're not fragmenting an outgoing NDP packet that out-ipv6-packets doesn't know exists at all. I see this as a more misleading set of semantics - but it's not worth the performance hit to have a special app _just_ to make those counters have those semantics, so this is the next best trade-off. If it's what you want, and we carefully document the non-intuitive bits (and what the counters are relevant to), it's what we'll do. :-)

**Comment by dpino** [comment]
There are several counters files which are committed as empty. These files are not used in the end-to-end.sh tests. IMHO these files should be removed. The files are:

counters/drop-misplaced-ipv4.lua
counters/in-1p-ipv4-out-1p-ipv6-5.lua
counters/nofrag4-ping.lua
counters/nofrag6-filterdrop.lua

Besides that, LGTM

**Pull request merged**
