### PR TITLE
Switch all code to intel_mp

### PR DESCRIPTION
**Pull request by teknico**
Switch all the various Snabb programs to use the `intel_mp` driver instead of `intel10g`.

Checklist:

  - [x] Convert apps to use `intel_mp`
  - [x] Fix segfault on `nfvconfig` selftest
  - [x] Stop `packetblaster` from relying on `intel10g` internals

### CODE REVIEW

**Comment by takikawa** [comment]
Rebased and force pushed since CI was failing to run.

**Comment by takikawa** [comment]
There's a test failure currently in the selftest of `program.snabbnfv.nfvconfig`. Looks like the problem is that we have this difference between `intel10g` and `intel_mp` in supporting different numbers of VMDq pools. `intel_mp` currently uses 32 pools to get more RSS queues. The test requires up to 64 pools though (see output of `grep "port_id" program/snabbnfv/test_fixtures/nfvconfig/scale_up/x | wc -l`).

Looks like maybe we should just set `intel_mp` to also use 64 pools (and up to 2 instead of 4 RSS queues) to make the tests pass since we weren't planning on using VMDq + RSS anyway.

How does that sound? CC @teknico

**Comment by teknico** [comment]
@takikawa, it sounds good to me, let's see what happens.

**Comment by teknico** [comment]
After fixing the `intel_mp` and `lib.ctable` tests, the `snabbnfv` one is now sometimes passing, sometimes not with a "PING failed" error again.

**Comment by takikawa** [comment]
Made progress on the tests by fixing a VLAN configuration bug. The snabbnfv selftest is now passing. There seems to be snabbvmx tests that are failing now though (potentially related to the loadgen changes---reverting that part seems to make the test pass on snabb1 but I haven't looked into it very closely).

**Comment by teknico** [comment]
It... is... GREEEN!!! :-D

**Comment by teknico** [comment]
Superseded by https://github.com/snabbco/snabb/pull/1199 .

**Pull request closed without merging**
