### PR TITLE
Remove the 'lwaftr generator' command

### PR DESCRIPTION
**Pull request by teknico**
Implement #503:
- remove the 'lwaftr generator' command;
- move the `packetblaster lwaftr` command support code from `src/apps/test/` to the command directory;
- add docs for using the `packetblaster lwaftr` command in place of the 'lwaftr generator' one.

### CODE REVIEW

**Comment by kbara** [comment]
LGTM

**Comment by dpino** [comment]
I am OK with the PR if "packetblaster lwaftr" is extended to generate packets of 550 bytes as "lwaftr generator" does. I think that change, as well as this PR and #509 should all be part of the same PR, because it's an atomic change. But anyway, if that comes in a different PR I'm ok with merging this PR and #509.

**Comment by teknico** [comment]
@dpino, as @mwiget mentioned, the `packetblaster lwaftr` command already has a `--size` parameter. I tried it and it seems to work. Does it do what you were thinking of?

**Comment by teknico** [comment]
And I split the changes in two to make more easily reviewable, but if you (@dpino) feel strongly that it should all be one change, I can merge them.

**Comment by teknico** [comment]
All done. @dpino, please have another look.

**Comment by dpino** [comment]
@teknico OK, in that case neglect my comment. Sorry for the noise. LGTM.

**Pull request merged**
