### PR TITLE
Call flush_hairpin if link is PKT_HAIRPINNED

### PR DESCRIPTION
**Pull request by dpino**
Fixes https://github.com/Igalia/snabb/issues/409

### CODE REVIEW

**Comment by kbara** [comment]
This needs to have a test case that triggers the problem added to the test suite, to serve as a regression test.

**Comment by kbara** [comment]
The checksums in all the PCAPs are incorrect. Please only use pcaps with valid checksums in every packet unless the invalid checksum is the point of the test - which it is not in this case.

**Comment by dpino** [comment]
I removed the test, as it became redundant with soaktest.

**Comment by kbara** [comment]
Please do not remove the test. It takes under a second to run, and the whole point is to be a regression test in case something similar breaks again in the future. Having slightly overlapping test coverage is not a bug.

**Comment by dpino** [comment]
We have a test case like this (with 1 packet) in end-to-end test to validate lwAFTR logic.

I think it was OK to have a test with repeated input when we didn't have the soaktest utility, but now this regression is detected by soaktest. This is what happens when I run soaktest without this patch:

```
Testing: from-to-b4 IPv6 packet, with hairpinning
loading compiled binding table from ../data/binding-table.o
compiled binding table ../data/binding-table.o is up to date.
apps/lwaftr/binding_table.lua:170: 'struct 1859' cannot be indexed with 'nil'
stack traceback:
        core/main.lua:130: in function '__index'
        apps/lwaftr/binding_table.lua:170: in function 'enqueue_lookup'
        apps/lwaftr/lwaftr.lua:532: in function 'enqueue_lookup'
        apps/lwaftr/lwaftr.lua:573: in function 'from_inet'
        apps/lwaftr/lwaftr.lua:889: in function 'method'
        core/app.lua:87: in function 'with_restart'
        core/app.lua:335: in function 'thunk'
        core/histogram.lua:98: in function 'breathe'
        core/app.lua:273: in function 'main'
        program/lwaftr/soaktest/soaktest.lua:47: in function 'run'
        program/lwaftr/lwaftr.lua:17: in function 'run'
        core/main.lua:49: in function <core/main.lua:36>
        [C]: in function 'xpcall'
        core/main.lua:172: in main chunk
        [C]: at 0x00452bc0
        [C]: in function 'pcall'
        core/startup.lua:3: in main chunk
        [C]: in function 'require'
        [string "require "core.startup""]:1: in main chunk
Test failed: Test failed: ../../../../snabb lwaftr soaktest ../data/no_icmp.conf
```

It's not a sightly overlap test it's actually the same test (tcp-fromb4-tob4-ipv6.pcap packet sent several times). I would like to keep end-to-end tests for verifying the lwAFTR logic and now having soaktest to detect system crashes, etc.

In addition, soaktest has detected the same failure in other test cases too such as 
"NDP: Without receiving NA, next_hop6_mac not set" and "NDP: With receiving NA, next_hop6_mac not initially set". Would that mean we should add new end-to-end cases with repeated input for this failing test cases too? I believe we should not as it's already covered by soaktest.

**Comment by kbara** [comment]
I think having -one- test in the main test suite covering it is useful, in case we ever disable the soaktests in CI (for instance, if we make them run for a really long time). I agree that we don't need a regression test for every analogous failure.

**Comment by dpino** [comment]
Reintroduced test.

**Review by kbara — APPROVED** [review]
LGTM

**Pull request merged**
