### PR TITLE
Add 'snabb-lwaftr' executable and packetblaster generator

### PR DESCRIPTION
**Pull request by dpino**
* `bin/snabb-lwaftr`: LwAftr executable. It can be executed from any location as long as 'snabb' executable is within PATH.
* `bin/snabb-lwaftr-blaster`: Reads IPv4 and IPv6 pcap files and flushes packetraffic traffic to NICs.
* `bin/snabb-lwaftr.inc.sh`: Helper functions.

### CODE REVIEW

**Comment by kbara** [comment]
Overall, nice work. Several nits:
a)  "error "Couldn't find configuratoin file" has a typo in configuration
b) Please check that the scripts are being run as root
c) Please make the lack of setting the PCI details fatal; it should not fall back to something which is extremely unlikely to be right for the machine anyone else is running it on.
d) Please make the default input files the 550 byte pcaps, not the larger ones.
e) Please get rid of "local SNABB_SRC=~/snabbswitch/src"; this is highly unlikely to be correct for other people running the scripts.

**Comment by dpino** [comment]
Updated PR, PTAL. I placed the root guard after the parameter processing so it's still possible to run the "--help" option without being root.

**Comment by kbara** [comment]
More nits:
a) The blaster doesn't fail gracefully if a specified nic is already in use; one nic blasts along happily, one gives a traceback:
```
$ sudo ./snabb-lwaftr-blaster --ipv4  ~/snabbswitch/tests/apps/lwaftr/benchdata/ipv0550.pcap --ipv6 ~/snabbswitch/tests/apps/lwaftr/benchdata/ipv6-0550.pcap --nic-inet 01:00.0 --nic-b4 02:00.1
failed to lock /sys/bus/pci/devices/0000:01:00.0/resource0
lib/hardware/pci.lua:114: assertion failed!
stack traceback:
	core/main.lua:116: in function <core/main.lua:114>
	[C]: in function 'assert'
	lib/hardware/pci.lua:114: in function 'map_pci_memory'
	apps/intel/intel10g.lua:89: in function 'open'
	apps/intel/loadgen.lua:20: in function 'new'
	core/app.lua:165: in function <core/app.lua:162>
	core/app.lua:197: in function 'apply_config_actions'
	core/app.lua:110: in function 'configure'
	program/packetblaster/packetblaster.lua:51: in function 'run'
	core/main.lua:56: in function <core/main.lua:32>
	[C]: in function 'xpcall'
	core/main.lua:121: in main chunk
	[C]: at 0x0044e580
	[C]: in function 'pcall'
	core/startup.lua:1: in main chunk
	[C]: in function 'require'
	[string "require "core.startup""]:1: in main chunk
```

b) The arguments should be renamed. --ipv4 doesn't sound like a parameter that should take a pcap file, for instance, and the NIC on the internal network is questionably enough called b4side in places, but calling it straight out nic-b4 is pushing that too far. Maybe --v4-pcap, --v6-pcap, --v6net-pci, and --v4net-pci? (Also not great names, admittedly).

**Comment by dpino** [comment]
Fixed issues and rebased.

I ended up named the card parameters, `v4-pci` and `v6-pci` so it's consistent with `v4-pcap  and `v6-pcap`. I made the change in both files.

Other changes:
* Minor case variables names (major case is only used for env variables).
* Removed the --kill argument. Trap SIGINT and free cards.
* Use single-bracket instead of double-brackets where possible.

**Comment by kbara** [comment]
Nice. Given that these are the preferred front-end for running our tools, they should probably be in a snabbswitch/bin directory, rather than so far the tree. I'm also wondering whether they should try to guess if snabb has been compiled and say if not, but perhaps not.

**Comment by dpino** [comment]
Done. I moved the scripts into `snabbswitch/bin`. Path `bin` was included in `.gitignore`, so I had to remove it.

**Comment by kbara** [comment]
Merged, thank you.

**Pull request merged**
