### PR TITLE
Import packet generation tool

### PR DESCRIPTION
**Pull request by aperezdc**
The `pktgen` tool is to be used to generate pcap files which contain traffic patterns modelled after those which can be found in actual networks. The generated pcap files can then be used to test the different applications using them.
    
The shape of the generated traffic is defined in a declarative way, using “packet spec files”, which look like the following (minimal) example:

```cfg
ip { tcp { .flags "", randbytes { .size 50 } } }
```

The above examples generates IPv4 packets with a TCP payload, and that in turn with a payload of 50 randomly-generated bytes. The block items which content with different network encapsulation map to their [Scapy](http://www.secdev.org/projects/scapy/) equivalents, and configuration attributes (e.g. `.flags`) allowed are the same accepted by the constructors of the corresponding Scapy classes.
    
In order to allow reusing spec files, it is possible to include a spec file from another using the `spec-file` element. For example the following reuses the spec file for TCP packets to create spec files for encapsulating them with IPv4 and IPv6:

```cfg
# file: tcp-randbytes.pktinc
tcp { .flags "", randbytes { .size 50 } }
    
# file: ipv4-tcp-randbytes.pktspec
ipv4 { spec-file { .name "tcp-randbytes" } }
    
# file: ipv6-tcp-randbytes.pktspec
ipv6 { spec-file { .name "tcp-randbytes" } }
```    

For a better use case, check the `imix*` files in the `examples/` subdirectory.

### CODE REVIEW

**Comment by kbara** [comment]
Overall, LGTM. It would be nice if:
- it'd show a user-friendly error message if someone tries to run it without scapy installed (but this is not a blocker to merging it)
- it had a README.pktgen that explained what you explained in the comment above, and which mentions that it depends on scapy.
Feel free to add a README and then hit 'merge'. :-)

**Comment by aperezdc** [comment]
I have just updated the PR description to match the current implementation of the tool.

**Comment by kbara** [comment]
Nifty tool; closing this PR since it doesn't match the packet generation needs of the lwaftr project, but keep it alive. :-)

**Comment by aperezdc** [comment]
As suggested, I have splitted this to [its own repository](https://github.com/aperezdc/pktgen)

**Pull request closed without merging**
