### PR TITLE
Add log-bucketed histogram, use it to record breathe() latencies

### PR DESCRIPTION
**Pull request by wingo**
The feature is currently only wired up to snabb lwaftr bench, where you
can turn it on by passing --measure-latency.

### CODE REVIEW

**Comment by dpino** [comment]
Read the source. Very nice, no comments. I imagine the size of the bucket and other constants will be parametrized in a final version. As you are localizing several math functions, there's a call to `math.exp` in `report` which can be localized too.

**Comment by wingo** [comment]
Tx for review.  I'm not so concerned about report() perf because it should happen in a separate process, I think.  Latest commit makes snabb top read latency files; will submit upstream.

**Comment by kbara** [comment]
LGTM, very nice work.

**Comment by wingo** [comment]
Tx for feedback.  Closing this one in favor of https://github.com/SnabbCo/snabbswitch/issues/777; if we want to merge, we should merge that branch IMO.

**Pull request closed without merging**
