### PR TITLE
IPv4 RFC791 packet reassembly

### PR DESCRIPTION
**Pull request by aperezdc**
This implements IPv4 reassembly, including unit tests.

The only thing that is not handled is overlapping fragments: the RFC allows for a fragments to overlap, and in that case for the overlapping fragments the one most recently received is to be used, but the packets passed to the reassembly function do not have timestamps, and therefore we cannot decide which version of the overlapping fragment to use. For now, when an overlapping segment is detected, `REASSEMBLE_INVALID` is returned.

### CODE REVIEW

**Comment by aperezdc** [comment]
Updated, PTAL.

**Comment by kbara** [comment]
Please cherry-pick b2949969ccb2752f3df783a9b2c9fdcbbf323c05 from test_ipv4_reassembly onto this branch.

**Comment by kbara** [comment]
After that, LGTM.

**Comment by aperezdc** [comment]
@kbara Done, I have cherry-picked the commit from the `test_ipv4_reassembly` branch and the PR is now updated.

**Comment by aperezdc** [comment]
Rebased against current `lwaftr_olive` branch, and added an additional commit which adds testing of the reassembly code for packets using 802.1Q VLAN tagging.

**Comment by aperezdc** [comment]
PR #116 contains a backport of this code for the `lwaftr_nutmeg` branch, and the code review has pointed some cleanups. I will be also applying them to this PR, so let's not merge it just yet, but after I get to update it later today.

**Pull request merged**
