### PR TITLE
Implement snabb config apps

### PR DESCRIPTION
**Pull request by wingo**
This PR implements the "config leader" and "config follower" apps, the private protocol between them, and the public protocol between the config leader and end-user routines like "snabb config get-config".

See https://github.com/snabbco/snabb/issues/1069 for design.  See #562 for the bigger picture.

To do:

- [x] Implement follower app and private protocol.

- [x] Properly implement the get-config RPC; will require that the config leader knows what YANG schema(s) are supported by the application.

- [x] ~Allow the lib.equal() O(n) check in app.compute_configuration_actions to be overridden (?), or otherwise check that it actually works with FFI data structures like the binding table.~ (Seems to work for now; O(n) is fine on a full reload because you don't know what changed, without hash-consing or something like that.)

- [x] Implement a load-config RPC that takes a file name.  That will finally make it so that we can reload configurations from disk again.

### CODE REVIEW

**Comment by wingo** [comment]
Latest commits add on support for message serialization for leader-follower protocol.  Next up is to implement the ring buffer and the follower app.

**Comment by wingo** [comment]
Ready for review!  With this one landed we just need to add support for paths and implement the set-config etc RPCs/command-line tools and we are there for milestone v3.0.

**Comment by tsyesika** [comment]
LGTM - with the caviat that i've not run and tested it for myself.

**Comment by wingo** [comment]
Thanks for the review!  Now to make it work like the documentation says it should :)

**Pull request merged**
