### PR TITLE
Reduced the number of globals

### PR DESCRIPTION
**Pull request by kbara**
This patch localizes two constants, adds two imports, removes a stale
import, and renames a variable to avoid shadowing an upvalue.

### CODE REVIEW

**Comment by kbara** [comment]
After this patch:

```
% luacheck lwaftr.lua                           
Checking lwaftr.lua                               Failure

    lwaftr.lua:241:1: setting non-standard global variable LwAftr
    lwaftr.lua:243:10: mutating non-standard global variable LwAftr
    lwaftr.lua:243:20: unused argument self
    lwaftr.lua:245:40: accessing undefined variable LwAftr
    lwaftr.lua:273:10: mutating non-standard global variable LwAftr
    lwaftr.lua:276:10: mutating non-standard global variable LwAftr
    lwaftr.lua:813:10: mutating non-standard global variable LwAftr

Total: 7 warnings / 0 errors in 1 file
```

**Review by teknico — APPROVED** [review]
I like it. :-)

**Comment by teknico** [comment]
I wonder whether anything quick can be done for some of those seven warnings too...

**Comment by kbara** [comment]
Not afaik, unfortunately.

**Pull request merged**
