### PR TITLE
Don't count tail calls towards loop unroll limit.

### PR DESCRIPTION
**Pull request by wingo**
See https://github.com/SnabbCo/snabbswitch/pull/707 for the Snabb PR and the link to the LuaJIT PR.

### CODE REVIEW

**Comment by andywingo** [comment]
The push doesn't pass as it's against upstream master, not lwaftr_rambutan, and so there is no travis yml file.  The PR test is the one to watch, and it passes.

**Comment by dpino** [comment]
Based on feedback from https://github.com/LuaJIT/LuaJIT/pull/123, should we still go ahead this change?

**Comment by kbara** [comment]
I'd vote 'no'. Mike Pall was quite clear, and I think he's right. The question is what we do instead.

**Comment by wingo** [comment]
On our branch, yes, no doubt.  It solves our problem without any drawback for our use case.  The LuaJIT maintainer recognizes that the check is bogus for tail calls, and we aren't using tail recursion.

**Comment by kbara** [comment]
I'm not willing to block this, given deadlines, so we'll merge it.

**Comment by wingo** [comment]
Merging, based on discussions in https://github.com/SnabbCo/snabbswitch/pull/707.

**Pull request merged**
