### PR TITLE
Fix extraction of source port from tunneled ICMP packets.

### PR DESCRIPTION
**Pull request by wingo**
Thanks to Marcel Wiget for the report and initial fix.

### CODE REVIEW

**Comment by dpino** [comment]
I think it handles Section 8.1 of the spec:

```
8.1.  ICMPv4 Processing by the lwAFTR

   For inbound ICMP messages, the following behavior SHOULD be
   implemented by the lwAFTR to provide ICMP error handling and basic
   remote IPv4 service diagnostics for a port-restricted CPE:

   1.  Check the ICMP Type field.

   2.  If the ICMP Type field is set to 0 or 8 (echo reply or request),
       then the lwAFTR MUST take the value of the ICMP Identifier field
       as the source port and use this value to look up the binding
       table for an encapsulation destination.  If a match is found, the
       lwAFTR forwards the ICMP packet to the IPv6 address stored in the
       entry; otherwise, it MUST discard the packet.
```

https://tools.ietf.org/html/rfc7596

**Comment by wingo** [comment]
Well, apparently this doesn't bork our end-to-end tests.  I'll file another issue to add a test for this case but merge it now for the v2.0 milestone.

**Comment by kbara** [comment]
I think this is an improvement (ie, it's probably a fix for ICMP error messages), but wrong for ping (echo requests).
```
 The lwB4 MUST implement the requirements defined in [RFC5508] for
   ICMP forwarding.  For ICMP echo request packets originating from the
   private IPv4 network, the lwB4 SHOULD implement the method described
   in [RFC6346] and use an available port from its port set as the ICMP
   identifier.
```
We need proper test cases for both types of ICMPv4-in-IPv6 (informative with ICMP identifiers as ports/error with grabbing it from the embedded packet), after confirming what happens with an actual B4.

*If* we're ok with the implications of merging code with a copyright we can't reassign into the core of the system, this patch LGTM. It's not complete, and I'd like to more strenuously verify that it's right (I think it very likely is), but as CI shows, it certainly is not a regression.

**Comment by kbara** [comment]
LGTM. Thank you.

**Comment by wingo** [comment]
tx for review!

**Pull request merged**
