### PR TITLE
Add "snabb config bench"

### PR DESCRIPTION
**Pull request by wingo**
From the README:

```
 Usage: snabb config bench [OPTION]... INSTANCE FILE
Benchmark "snabb listen" by repeatedly feeding it commands from FILE.

Available options:
  -h, --help                 Display this message.
  -s, --schema SCHEMA        YANG data interface to request.
  -r, --revision REVISION    Require a specific revision of the YANG module.

This command will fork off a "snabb config listen INSTANCE" child
process, passing it the -s and -r options.
```

Invoke like this:

```
$ sudo ./snabb config bench lwaftr /tmp/commands2.json
........................................................
Issued 56 commands in 0.59 seconds (95.14 commands/s)
```

That's with a running "snabb lwaftr bench" with the name "lwaftr".  The commands2.json in this case is a file containing this, 56 times:

```json
{"id":"foo","verb":"get","path":"/softwire-config/external-interface/mtu"}
```

This PR has some performance tweaks as well, basically memoizing more things.  Perhaps the memoization should have a cache eviction policy though.  WDYT @dpino?

### CODE REVIEW

**Comment by wingo** [comment]
Incidentally to get top performance, we need to increase Hz in leader.lua and also pipeline requests.  Without pipelining and with 20e3 Hz instead of 1e3 Hz I get 5e2 requests/s instead of 1e2 requests/s.  I expect pipelining to put me in the range of 5e3 or 5e4. I will add some related options to "snabb config bench" to enable pipelining.

**Comment by kbara** [comment]
LGTM once CI passes.

**Comment by wingo** [comment]
With this change I get 8e3 simple "get-config" results per second, which is sufficient for that use case.

**Comment by kbara** [comment]
LGTM once tests pass.

```
src/testlog/program.lwaftr.selftest.sh:
Testing snabb lwaftr bench
program/lwaftr/tests/data//icmp_on_fail.conf: loading compiled configuration from program/lwaftr/tests/data//icmp_on_fail.o
core/main.lua:26: incompatible version: 4096
```

**Pull request merged**
