### PR TITLE
Added ARP support to the lwaftr.

### PR DESCRIPTION
**Pull request by kbara**
This is similar to the support for NDP:
- arp.lua forms request and reply packets
- ipv4_apps.lua handles policy in the ARP app
- setup.lua glues it into the lwaftr's app network.

### CODE REVIEW

**Comment by plajjan** [comment]
@kbara you mentioned at some point that  nd_light didn't meet your requirements/expectations so you decided to write your own, what were the reasons for that? I'm trying to understand the real driver for not using it and not doing an equivalent for ARP?

**Comment by kbara** [comment]
It had several baked in assumptions that didn't match our needs - for instance, the lwaftr needs to support having multiple IPv6 addresses - and it was written in a beautiful but somewhat awkward to modify way. I spent a while modifying it, but just kept running into little mismatches that were annoying to untangle - hence eventually deciding to write my own, intentionally making it go to the other extreme in terms of policy/implementation decoupling.
It's good code, nicely written, just... different enough in assumptions that it was much more time-consuming than it looked to use for our needs.

**Comment by wingo** [comment]
How did this work?  The CL seems to be missing `tunnel_icmp_without_mac4_vlan.conf`, and so the tests in https://github.com/Igalia/snabb/pull/301 are failing; how were they succeeding here, I wonder?

**Comment by wingo** [comment]
fixed in https://github.com/Igalia/snabb/pull/302

**Pull request merged**
