### PR TITLE
Rewrite loop using C.memmove

### PR DESCRIPTION
**Pull request by dpino**
Copying the data using C.memmove removes garbage collection cycles (as reported by LuaJIT's profiler), improving performance. However, for small size packets, it seems C.memmove is slower than copying the data directly with a loop. So, I added an heuristic to determine whether to use C.memmove or a loop.

More precisely, the first test below decreased it's performance (to 3.5) if C.memmove was used (the tests uses a packet size of 28. I set the threshold to 32 but actually I don't have data to know what's the right value).

Before:                                                                         
         
```                                                                       
Benchmarking: from-internet IPv4 packet found in the binding table,             
needs IPv6 fragmentation, DF set, ICMP-3,4.                                     
Rate(Mpps): 0.495                                                               
Benchmarking: from-b4 to-internet IPv6 packet NOT found in the binding          
table (ICMP-on-fail)                                                            
Rate(Mpps): 0.720                                                               
```
                                                                            
After:                                                                          

```                                                                                
Benchmarking: from-internet IPv4 packet found in the binding table,             
needs IPv6 fragmentation, DF set, ICMP-3,4.                                     
Rate(Mpps): 0.493                                                               
Benchmarking: from-b4 to-internet IPv6 packet NOT found in the binding          
table (ICMP-on-fail)                                                            
Rate(Mpps): 1.141             
```

### CODE REVIEW

**Comment by kbara** [comment]
I'm hesitant about this, especially as it introduces a conditional. I'd want to see how it did on a mixture of input packets; the current benchmark always takes one branch, so falsely hides that penalty.

**Comment by dpino** [comment]
Agree, I can do a test that sends both types of packets and see how it goes.  @kbarone What do you think?

**Comment by kbara** [comment]
Sounds good. The way it's currently being done definitely has to go; the question is whether or not to unconditionally memmove, as I see it. Thanks!

**Comment by dpino** [comment]
Updated PR. I tested with a pcap file contain both types of packets. These are the results:

**With conditional** (Lua loop or C.memmove depending on packet size)

```
$ sudo ./benchmark-end-to-end.sh 0000:04:00.0 | grep -e "Benchmarking\|Rate"
Benchmarking: from-internet IPv4 packet found in the binding table, needs IPv6 fragmentation, DF set, ICMP-3,4.
Rate(Mpps): 0.681
Benchmarking: from-b4 to-internet IPv6 packet found in the binding table.
Rate(Mpps): 0.623
```

Avg: 0.652 Mpps


**Only C.memmove**

```
$ sudo ./benchmark-end-to-end.sh 0000:04:00.0 | grep -e "Benchmarking\|Rate"
Benchmarking: from-internet IPv4 packet found in the binding table, needs IPv6 fragmentation, DF set, ICMP-3,4.
Rate(Mpps): 0.937
Benchmarking: from-b4 to-internet IPv6 packet found in the binding table.
Rate(Mpps): 0.870
```

Avg: 0.9035 Mpps


**Only Lua loop**

```
$ sudo ./benchmark-end-to-end.sh 0000:04:00.0 | grep -e "Benchmarking\|Rate"
Benchmarking: from-internet IPv4 packet found in the binding table, needs IPv6 fragmentation, DF set, ICMP-3,4.
Rate(Mpps): 0.691
Benchmarking: from-b4 to-internet IPv6 packet found in the binding table.
Rate(Mpps): 0.497
```

Avg: 0.594 Mpps

It seems the best case if to always run C.memmove.

**Comment by kbara** [comment]
Perfect. That's what I expected, but it's always good to have actual measurements!

**Comment by kbara** [comment]
Mainly LGTM. I'm in favor of changing ```write_icmp(new_pkt, config)``` to ```write_icmp(new_pkt, config, 0)``` and getting rid of the 'or 0' code before merging, though.

**Comment by dpino** [comment]
@kbara Done

**Comment by kbara** [comment]
Sorry, one more nit: could you replace 8 with constants.ipv6_frag_header_size ?

**Comment by dpino** [comment]
@kbara: Sure. PR updated.

**Comment by kbara** [comment]
LGTM, thanks.

**Pull request merged**
