### PR TITLE
Added Lwaftr benchmark

### PR DESCRIPTION
**Pull request by dpino**
* src/apps/lwaftr/benchmark.lua: Added benchmark. Send a packet during n seconds. Aftr conf file and input pcap file with packet are passed as parameters. Settings of NICs should be adjusted according to aftr configuration file. Run as:
```
sudo ./snabb snsh apps/lwaftr/benchmark.lua \
   ../tests/apps/lwaftr/data/binding.table \
   ../tests/apps/lwaftr/data/icmp_on_fail.conf \
   ../tests/apps/lwaftr/data/tcp-frominet-bound.pcap \
   0000:04:00.0
```
* src/apps/lwaftr/lwaftr.lua: Put print and debug messages under a flag. Print out messages to the console affects benchmarking. 
* src/apps/lwaftr/lwutil.lua: Refactored print functions to dump + print.

### CODE REVIEW

**Comment by kbara** [comment]
I'm happy with benchmark.lua. I'm against adding a 'log' mechanism of the sort this patch introduces; these are short-term debug messages, and having that overhead makes no sense in the near future.

**Comment by dpino** [comment]
Printing out messages to console slows down the benchmark. I cannot progress in this task while there are messages printed out in stdout. In addition, some print messages are already guarded by a debug flag, why this logging mechanism is a worst solution? I can keep this commit on my local branch and keep progressing on the benchmark task but I wouldn't like to have to modify the source code again is new print messages are introduced. So, if you wouldn't like to integrate the patch, could you propose a solution to avoid printing logging messages?

**Comment by kbara** [comment]
I've turned debug off by default, made sure the tests still pass, and made all prints conditional on debug. If you modify the patch to just include the benchmarking code, I'll merge it. Thanks!

**Comment by dpino** [comment]
Pushed a 550-byte size version of 'tcp-frominet-bound.pcap'. Performance is almost the same as with normal version of the packet:

```
sudo ./snabb snsh apps/lwaftr/benchmark.lua ../tests/apps/lwaftr/data/binding.table ../tests/apps/lwaftr/data/icmp_on_fail.conf ../tests/apps/lwaftr/data/tcp-frominet-bound-550.pcap

Processed 0.2 million packets in 5.01 seconds (11620350 bytes; 0.02 Gbps)
Made 651 breaths: 255.00 packets per breath; 7690.58 us per breath
Rate(Mpps): 0.033
```

**Comment by kbara** [comment]
Looks better. I'd like to see usage info, and for pcidevA to be a parameter rather than hardcoded.

**Comment by dpino** [comment]
Updated PR with suggested changes.

**Comment by kbara** [comment]
Thanks! This is a quite useful first step in benchmarking. (We'll need to test with more varied packets at some point; this benchmark presumably paints an overly rosy view because the traces are always taking exactly the same conditionals, etc).

**Pull request merged**
