### PR TITLE
Add support for "snabb config set" with paths

### PR DESCRIPTION
**Pull request by wingo**
PTAL @xray7224.  Setting of table and array items is still unimplemented; the data parses fine but the leader doesn't have the update logic yet.

### CODE REVIEW

**Comment by wingo** [comment]
PTAL @xray7224, I think the "add" "remove" and "set" commands of `snabb config` are now functionality-complete.

**Comment by wingo** [comment]
The code is a bit nasty, unfortunately.  If you have any thought about how to factor things it's welcome.

**Comment by tsyesika** [comment]
I actually don't think the code is paticually nasty. I was wondering about changing some of the if statement blocks on `grammar.type` to the usual pattern of putting handlers in a table and then executing based on a lookup. You're often doing conditions which don't lend themselves to that unfortunately.

Otherwise it LGTM

**Comment by wingo** [comment]
Yeah.  I'm sure we'll revisit this code in the future, probably nicer patterns will become apparent.  Maybe we need to make our data structures look more uniform somehow to be able to make this code have fewer gnarlies.

**Pull request merged**
