### PR TITLE
[WIP] Add support for ietf-softwire

### PR DESCRIPTION
**Pull request by wingo**
The support code for the native schema can define translators for
operations phrased in terms of a "foreign schema".  It is assumed that
anything representable in any foreign schema is also representable in
the native schema: the native schema should be a superset of all foreign
schemas.  The snabb-softwire-v1 support code will define a translator for
ietf-softwire.

Design doc: #608.

### CODE REVIEW

**Comment by wingo** [comment]
As usual recently, the `snabb1` is the bot to follow, not `snabb2`.  @dpino is going to fix that :)

Example output:

```
$ make && sudo ./snabb config get -s ietf-softwire lwaftr /
make: 'snabb' is up to date.
[sudo] password for wingo: 
softwire-config {
  binding {
    br {
      br-instances {
        br-instance {
          id 1;
          binding-table {
            binding-entry {
              binding-ipv6info 127:11:12:13:14:15:16:128;
              binding-ipv4-addr 178.79.150.233;
              br-ipv6-addr 8:9:a:b:c:d:e:f;
              port-set {
                psid 2700;
              }
            }
            binding-entry {
              binding-ipv6info 127:14:25:36:47:58:69:128;
              binding-ipv4-addr 178.79.150.3;
              br-ipv6-addr 1e:2:2:2:2:2:2:af;
              port-set {
                psid 4;
              }
            }
            binding-entry {
              binding-ipv6info 127:10:20:30:40:50:60:128;
              binding-ipv4-addr 178.79.150.1;
              br-ipv6-addr 8:9:a:b:c:d:e:f;
              port-set {
                psid 0;
              }
            }
            binding-entry {
              binding-ipv6info 127:24:35:46:57:68:79:128;
              binding-ipv4-addr 178.79.150.2;
              br-ipv6-addr 1e:1:1:1:1:1:1:af;
              port-set {
                psid 7850;
              }
            }
            binding-entry {
              binding-ipv6info 127:2:3:4:5:6:7:128;
              binding-ipv4-addr 178.79.150.233;
              br-ipv6-addr 8:9:a:b:c:d:e:f;
              port-set {
                psid 80;
              }
            }
            binding-entry {
              binding-ipv6info 127:22:33:44:55:66:77:128;
              binding-ipv4-addr 178.79.150.15;
              br-ipv6-addr 8:9:a:b:c:d:e:f;
              port-set {
                psid 0;
              }
            }
          }
          tunnel-path-mru 0;
          tunnel-payload-mtu 0;
        }
      }
    }
  }
}
```

This one is interesting, it's for the icmp_on_fail.conf, which sets up a number of softwires that have the same B4.  Not a problem for us, but it is for the model.  Perhaps when going to ietf-softwire we should assert that there are no duplicate b4 addresses.

**Comment by wingo** [comment]
Also, still missing support for get-state, set, add, and remove.  I will do those on Monday.

**Comment by dpino** [comment]
@wingo: I retook the task and I was trying to deploy snabb-bot on snabb2. Still no success :/

**Comment by wingo** [comment]
So this works now:
```
sudo ./snabb config add -s ietf-softwire lwaftr '/softwire-config/binding/br/br-instances/br-instance[id=1]/binding-table/binding-entry'
{
  binding-ipv6info 127:11:12:13:14:15:20:128;
  binding-ipv4-addr 178.79.21.233;
  br-ipv6-addr 8:9:a:b:c:d:e:f;
  port-set {
    psid 2700;
    psid-len 16;
    psid-offset 0;
  }
}
```

But this doesn't yet:

```
sudo ./snabb config remove -s ietf-softwire lwaftr '/softwire-config/binding/br/br-instances/br-instance[id=1]/binding-table/binding-entry[binding-ipv6info=127:11:12:13:14:15:20:128]'
```

**Comment by wingo** [comment]
With the last couple commits, the add/remove softwire fastpath appears to be working.

**Comment by wingo** [comment]
I tested: "get" on the whole thing, of the binding-entry table, and of leaves; "set" on the whole thing, on the binding-entry table as a whole, and on elements of individual binding entries (psid, psid params (should fails), ipv4, br address), and add/remove to binding-entry.

**Comment by tsyesika** [comment]
I thought I'd have a bunch of nits but looked through the code and it LGTM. I've also tested it locally and it works as expected. I've tested get, get-state, set, add and remove.

The get-state doesn't work, as in the counters don't show the correct values but it does work in the respect that it outputs a correctly formatted output, simply with zeroed counters. It might be worth noting that somewhere, i know it's intentional based on https://github.com/Igalia/snabb/pull/611/files#diff-45080012d47088b1d74a62f2fe672e98R247 but. I don't maybe this needs an issue or something.

Anyway. LGTM

**Comment by wingo** [comment]
thanks for the review @xray7224 !  I think I was missing the new counters, so for that reason I need `lwaftr` to implement the get-state stuff appropriately.  Will do.

**Pull request merged**
