### PR TITLE
Add "snabb ps"

### PR DESCRIPTION
**Pull request by wingo**

### CODE REVIEW

**Review by tsyesika — CHANGES_REQUESTED** [review]
This doesn't actually use `parse_args` so doing "-h" at commandline doesn't actually register with this command. I think you want to make some changes to run.

**Comment by wingo** [comment]
Lol thanks for catching that.  Do you think "snabb ps" is the right name?  Should we add any other output formats in the first version?  (Surely in the end we should prefer names over PIDs, right?)

**Comment by tsyesika** [comment]
I think names are quite important, I think most people will want to be referring to names over PIDs. With that said, until we add giving the lwaftr instances a name, I don't think it's as important.

I do think we probably should add the name attribute soon though.

**Review by tsyesika — APPROVED** [review]

**Comment by tsyesika** [comment]
LGTM

**Pull request merged**
