### PR TITLE
Add new load testing application

### PR DESCRIPTION
**Pull request by wingo**
Example output, with nothing running on the other side:

```
$ make && sudo ./snabb lwaftr loadtest program/lwaftr/tests/benchdata/ipv4-0550.pcap IPv4 IPv6 83:00.0  program/lwaftr/tests/benchdata/ipv6-0550.pcap IPv6 IPv4 83:00.1
LUA       obj/program/lwaftr/loadtest/promise_lua.o
LUA       obj/program/lwaftr/loadtest/loadtest_lua.o
LINK      snabb
BINARY    2.3M snabb
LINK      snabb-lwaftr
Warming up at 5.000000 Gb/s for 2 seconds.
Applying 1.000000 Gbps of load.
  IPv4:
    TX 1136364 packets (0.227273 MPPS), 625000200 bytes (1.000000 Gbps)
    RX 3 packets (0.000001 MPPS), 498 bytes (0.000001 Gbps)
    Loss: 1136361 packets (99.999736%)
  IPv6:
    TX 1136364 packets (0.227273 MPPS), 625000200 bytes (1.000000 Gbps)
    RX 4 packets (0.000001 MPPS), 558 bytes (0.000001 Gbps)
    Loss: 1136360 packets (99.999648%)
Applying 2.000000 Gbps of load.
  IPv4:
    TX 2272727 packets (0.454545 MPPS), 1249999850 bytes (2.000000 Gbps)
    RX 4 packets (0.000001 MPPS), 250 bytes (0.000000 Gbps)
    Loss: 2272723 packets (99.999824%)
  IPv6:
    TX 2272727 packets (0.454545 MPPS), 1249999850 bytes (2.000000 Gbps)
    RX 3 packets (0.000001 MPPS), 190 bytes (0.000000 Gbps)
    Loss: 2272724 packets (99.999868%)
Applying 3.000000 Gbps of load.
  IPv4:
    TX 3409089 packets (0.681818 MPPS), 1874998950 bytes (2.999998 Gbps)
    RX 3 packets (0.000001 MPPS), 498 bytes (0.000001 Gbps)
    Loss: 3409086 packets (99.999912%)
  IPv6:
    TX 3409089 packets (0.681818 MPPS), 1874998950 bytes (2.999998 Gbps)
    RX 3 packets (0.000001 MPPS), 498 bytes (0.000001 Gbps)
    Loss: 3409086 packets (99.999912%)
Applying 4.000000 Gbps of load.
  IPv4:
    TX 4545446 packets (0.909089 MPPS), 2499995300 bytes (3.999992 Gbps)
    RX 0 packets (0.000000 MPPS), 0 bytes (0.000000 Gbps)
    Loss: 4545446 packets (100.000000%)
  IPv6:
    TX 4545446 packets (0.909089 MPPS), 2499995300 bytes (3.999992 Gbps)
    RX 0 packets (0.000000 MPPS), 0 bytes (0.000000 Gbps)
    Loss: 4545446 packets (100.000000%)
Applying 5.000000 Gbps of load.
  IPv4:
    TX 5681810 packets (1.136362 MPPS), 3124995500 bytes (4.999993 Gbps)
    RX 0 packets (0.000000 MPPS), 0 bytes (0.000000 Gbps)
    Loss: 5681810 packets (100.000000%)
  IPv6:
    TX 5681810 packets (1.136362 MPPS), 3124995500 bytes (4.999993 Gbps)
    RX 0 packets (0.000000 MPPS), 0 bytes (0.000000 Gbps)
    Loss: 5681810 packets (100.000000%)
Applying 6.000000 Gbps of load.
  IPv4:
    TX 6818186 packets (1.363637 MPPS), 3750002300 bytes (6.000004 Gbps)
    RX 1 packets (0.000000 MPPS), 368 bytes (0.000001 Gbps)
    Loss: 6818185 packets (99.999985%)
  IPv6:
    TX 6818186 packets (1.363637 MPPS), 3750002300 bytes (6.000004 Gbps)
    RX 1 packets (0.000000 MPPS), 368 bytes (0.000001 Gbps)
    Loss: 6818185 packets (99.999985%)
Applying 7.000000 Gbps of load.
  IPv4:
    TX 7954547 packets (1.590909 MPPS), 4375000850 bytes (7.000001 Gbps)
    RX 0 packets (0.000000 MPPS), 0 bytes (0.000000 Gbps)
    Loss: 7954547 packets (100.000000%)
  IPv6:
    TX 7954547 packets (1.590909 MPPS), 4375000850 bytes (7.000001 Gbps)
    RX 0 packets (0.000000 MPPS), 0 bytes (0.000000 Gbps)
    Loss: 7954547 packets (100.000000%)
Applying 8.000000 Gbps of load.
  IPv4:
    TX 9090900 packets (1.818180 MPPS), 4999995000 bytes (7.999992 Gbps)
    RX 0 packets (0.000000 MPPS), 0 bytes (0.000000 Gbps)
    Loss: 9090900 packets (100.000000%)
  IPv6:
    TX 9090900 packets (1.818180 MPPS), 4999995000 bytes (7.999992 Gbps)
    RX 0 packets (0.000000 MPPS), 0 bytes (0.000000 Gbps)
    Loss: 9090900 packets (100.000000%)
Applying 9.000000 Gbps of load.
  IPv4:
    TX 10227282 packets (2.045456 MPPS), 5625005100 bytes (9.000008 Gbps)
    RX 0 packets (0.000000 MPPS), 0 bytes (0.000000 Gbps)
    Loss: 10227282 packets (100.000000%)
  IPv6:
    TX 10227282 packets (2.045456 MPPS), 5625005100 bytes (9.000008 Gbps)
    RX 0 packets (0.000000 MPPS), 0 bytes (0.000000 Gbps)
    Loss: 10227282 packets (100.000000%)
Applying 10.000000 Gbps of load.
  IPv4:
    TX 10863357 packets (2.172671 MPPS), 5974846350 bytes (9.559754 Gbps)
    RX 0 packets (0.000000 MPPS), 0 bytes (0.000000 Gbps)
    Loss: 10863357 packets (100.000000%)
  IPv6:
    TX 10863534 packets (2.172707 MPPS), 5974943700 bytes (9.559910 Gbps)
    RX 0 packets (0.000000 MPPS), 0 bytes (0.000000 Gbps)
    Loss: 10863534 packets (100.000000%)
```

### CODE REVIEW

**Comment by dpino** [comment]
Excellent! LGTM

**Comment by lukego** [comment]
wow awesome idea! cc @eugeneia @capr who are also interested in performance testing.

One tiny idea is to use fewer significant digits e.g. to round `3.999992` to `4.000` to make the output easier to skim.

**Comment by lukego** [comment]
I know you are busy at the moment but here is a passing idea that we could discuss later:

The code on this feature branch seems like it could be equally interesting for all Snabb application developers and not specific to the lwAFTR. It would be cool to have a workflow that would publish this for the whole community but without slowing down your work.

Here is one way that could be done:

1. Base the feature branch on your common ancestor with master e.g. `git checkout -b loadtest v2016.01`. This would isolate the feature so that it could be cleanly merged onto many different branches (e.g. `lwaftr`, `max-next`, etc) without bringing along other changes.
2. Pull Request to the SnabbCo repo. Now everybody can see the code, anybody who wants it can merge it, and somebody will be assigned to accept it.
3. Merge the code onto `lwaftr` as soon as you are ready e.g. when another Igalian comments LGTM.
4. If you decide to make improvements while the PR is open then push those (and re-merge to `lwaftr` if important).
5. Code lands upstream e.g. on `max-next` and you are done.

This way the code is available to everybody from the beginning, it lands on the `lwaftr` branch just as quickly and subject to the same process as today, and when you PR the `lwaftr` branch upstream this code won't appear in the diff because it has already landed (unless we have been too slow to accept it which we will have to try and avoid).

... on the other hand then it would probably make sense to add this functionality to `packetblaster` rather than `lwaftr` and maybe it doesn't make sense for you to do it that way right now or you want to think about that later.

**Comment by lukego** [comment]
(Let me know if posting unsolicited ideas on closed PRs is suboptimal and e.g. I should hold off until you have the time and headspace to take the upstreaming discussion :-))

**Comment by kbara** [comment]
I really like it, as long as you're ok with not necessarily getting fast responses!

**Comment by lukego** [comment]
Sure :).

On reflection there is a simpler workflow available that can still be used i.e. add the new functionality into the `src/program/lwaftr` directory and merge discreetly onto `lwaftr` (as done here), then later merge the whole `lwaftr` upstream to master, then we have all the code in one place and somebody (anybody) could make a PR to refactor the functionality into `packetblaster` to make it more widely available.

**Comment by eugeneia** [comment]
I agree that it would be cool to merge this and `packetblaster`, seems that both applications have a lot of overlap as well as distinct features that the other one is lacking. :+1:

**Pull request merged**
