### PR TITLE
Update and clean up documentation

### PR DESCRIPTION
**Pull request by dpino**
- Document new features.
- Remove chapters that doesn't longer exist.
- Remove duplicated paragraphs.
- Rearrange manual in a more logical order.

### CODE REVIEW

**Comment by wingo** [comment]
lgtm

**Comment by wingo** [comment]
why did the tests fail?  v weird.

**Comment by dpino** [comment]
Dunno. It says:

src/testlog/apps.solarflare.selftest.sh:
obj/apps/solarflare/ef_vi_h.luah:502: unexpected symbol near 'include' at line 3
EXITCODE: 43

I will try to rerun the tests again.

**Comment by kbara** [comment]
Why did you get rid of all the stuff on NUMA?

**Comment by wingo** [comment]
pretty sure the numa stuff was duplicated in two places; see readme.performance.md for its new home

**Pull request merged**
