### PR TITLE
Add core.version module and --version command-line argument

### PR DESCRIPTION
**Pull request by wingo**
This is a version of https://github.com/snabbco/snabb/pull/1146 for `lwaftr-3.1`.  WDYT @xray7224 ?

### CODE REVIEW

**Comment by tsyesika** [comment]
LGTM.

**Comment by dpino** [comment]
LGTM. `snabb lwaftr` printed out the version number, which was retrieved from the lwaftr CHANGELOG file.

https://github.com/Igalia/snabb/blob/lwaftr/src/program/lwaftr/lwaftr.lua#L7

If possible, please remove the code that fetched and print the version number.

**Comment by wingo** [comment]
@dpino This PR is for the 3.1 branch, which doesn't include that code AFAIU.

**Comment by dpino** [comment]
@wingo OK, disregard my comment then. I created an issue (#815) to address that in the future.

**Pull request merged**
