### PR TITLE
VirtioNet

### PR DESCRIPTION
**Pull request by dpino**
This is #681 rebased to `lwaftr_rambutan` (upstream PR cannot be merged smoothly, needed some changes). I tested it and it's working fine. The results below is the performance for the virtio_net driver (not the lwaftr) (packet size: 510 bytes):

```
link report:
          41,569,390 sent on ixgb.tx -> sink.rx (loss rate: 0%)
load: time: 10.00s  fps: 2,316,318 fpGbps: 9.654 fpb: 5   bpp: 512  sleep: 0   us
link report:
          64,732,690 sent on ixgb.tx -> sink.rx (loss rate: 0%)
load: time: 10.00s  fps: 2,319,483 fpGbps: 9.668 fpb: 5   bpp: 512  sleep: 0   us
```

### CODE REVIEW

**Comment by dpino** [comment]
It covers checkpoint 1) in #199

**Comment by kbara** [comment]
Awesome! Out of curiosity, how does it do on, say, 128-byte packets?

**Comment by kbara** [comment]
LGTM. One question: where are your changes with regard to the upstream PR? All 11 commits say "nnikolaev-virtualopensystems committed with dpino".

**Comment by kbara** [comment]
Also, for future reference, will you put the command you used to get that link report here? :-)

**Comment by dpino** [comment]
@kbara Unfortunately not well. I don't recall the exact numbers for 128-bytes but for 256-bytes perf is around 5.7 Gbps. It seems the problem is that the main loop is running in interpreted mode. I'm looking into that but no patches yet.

**Comment by kbara** [comment]
Ok, good to know.

**Comment by kbara** [comment]
LGTM.

**Comment by dpino** [comment]
With regard to the changes, the difference was to solve merge conflicts in core/lib.lua with the function "compile_memory_barrier", because it was added at the bottom too, as some other functions in the PR.

**Comment by dpino** [comment]
Thanks :)

**Pull request merged**
