### PR TITLE
Separate test-data from core-end-to-end.sh

### PR DESCRIPTION
**Pull request by dpino**
Moves test data into its own file so it can be reused in other tests.

### CODE REVIEW

**Comment by teknico** [comment]
More Bash logic, sigh. LGEBNRGTM (Looks Good Enough, But Not Really Great, To Me)

**Comment by dpino** [comment]
I can explain more about the motivation for this change.

We want to add a new type of test called soaktest. What basically does is to run the same test cases as the end-to-end tests, but instead of verifying the output generated by the lwAFTR, it runs on a given input repeatedly for a certain period of time verifying there were no crashes.

Currently test cases are coupled with end-to-end testing (lwaftr check). What the PR does is to move the test data to a separate file. Test data is now stored as an array so it can be easily retrieved. For instance:

``` bash
TEST_DATA=(
"from-internet IPv4 packet found in the binding table."
"icmp_on_fail.conf" "tcp-frominet-bound.pcap" "" "" "tcp-afteraftr-ipv6.pcap"
"in-1p-ipv4-out-1p-ipv6-1.lua"

"from-internet IPv4 packet found in the binding table with vlan tag."
"vlan.conf" "tcp-frominet-bound-vlan.pcap" "" "" "tcp-afteraftr-ipv6-vlan.pcap"
"in-1p-ipv4-out-1p-ipv6-1.lua"

...
```

In the array, a test-case is represented by a group of 3 rows. What it matters is that a test case is actually 7 fields of data (test name, conf, in_v4, in_v6... etc). Spaces and new lines don't count.

After this change, core-end-to-end.sh loops over the array of test data and runs every test.

**Comment by teknico** [comment]
Yes, that's what I surmised from the code. It would be useful to put the part about the seven fields as comments in the relevant script, as documentation.

**Comment by kbara** [comment]
All else being equal, I'd rather just have the test cases run $SNABB_TEST_PROGRAM rather than snabb_run_and_cmp and have the calling scripts set that. I don't see how using arrays of (as @teknico said) undocumented arguments is a win; it requires more bash logic for no real gain that I can see, for flexibility that we're not actually using.

Thoughts?

**Comment by dpino** [comment]
Honestly I prefer to keep this approach and document the structure of an array entry. Currently is neither possible to know what the arguments to a snabb_run_and_cmp call test mean unless reading the snabb_cmp function. The same can be done by reading `run_test` function in this patch.

On the other hand, replacing SNABB_TEST_PROGRAM with a different subprogram won't work because "lwaftr soaktest" expects a lower number of arguments than "lwaftr check".

**Comment by kbara** [comment]
Alright; let's do it this way.

**Review by kbara — APPROVED** [review]
Now that the fields are documented, LGTM

**Pull request merged**
