### PR TITLE
CPU parsing should return an empty list if string is blank

### PR DESCRIPTION
**Pull request by dpino**

### CODE REVIEW

**Comment by takikawa** [comment]
The change looks reasonable to me, but I'm not quite sure how to reproduce the issue. Is this for when `available_cpus` reads the system files and finds a blank file? Any reason to not also consider `""` as blank for example? (like in `./snabb lwaftr run --cpu "" ...` or something)

**Comment by dpino** [comment]
The error happens when there are not isolated CPUs in the system. In that case, the list of CPUs is an empty line. I agree the fix should also address an empty line. Possibly trimming the line is the right thing to do.

**Review by takikawa — APPROVED** [review]

**Comment by takikawa** [comment]
LGTM. Looks like CI failed but is it just the recent snabbnfv test flakiness?

**Comment by dpino** [comment]
I rerun CI and this time it passed all tests.

**Pull request merged**
