### PR TITLE
Reload binding table on SIGHUP

### PR DESCRIPTION
**Pull request by dpino**
Implemented reload of binding table on SIGHUP. How to test:

1) Run lwaftr:

```bash
sudo ./snabb-lwaftr run \
    --bt program/snabb_lwaftr/tests/data/binding.table \
    --conf program/snabb_lwaftr/tests/data/icmp_on_fail.conf \
    --v4-pci 0000:04:00.0 \
    --v6-pci 0000:05:00.0
```

2) Send signal SIGHUP to running snabb-lwaftr process:

```bash
sudo kill -SIGHUP `pidof snabb-lwaftr`
```

Result:

```
[snabb-lwaftr: SIGHUP caught - reload binding table]
```

The binding table gets reloaded.

### CODE REVIEW

**Comment by dpino** [comment]
This PR solves #89

**Comment by kbara** [comment]
LGTM. It's a bit unlike most of our coding conventions to abbreviate syscall to S, but I'm ok with that.

**Comment by lukego** [comment]
(I am okay with the S abbref in snabbswitch code too since it seems to be the idiomatic convention for other ljsyscall users.)

**Comment by dpino** [comment]
Thanks for the review. Merged.

**Pull request merged**
