### PR TITLE
Fixed incoming ICMPv6+hairpinning support

### PR DESCRIPTION
**Pull request by kbara**
If hairpinning is enabled, the source address and port of the original packet
must be checked to see if they are in the binding table. The wrong bytes were
being compared against binding table entries.

### CODE REVIEW

**Comment by kbara** [comment]
See https://github.com/Igalia/snabbswitch/issues/165 for more details.

**Comment by dpino** [comment]
LGTM.

**Comment by aperezdc** [comment]
LGTM, though I don't know all the details about hairpinning, the changes look good :+1:

**Comment by kbara** [comment]
@aperezdc I have some fancy diagrams in the office. I suppose I should scan them and maybe blog about it at some point, because it's something it'd be good for the whole team to know.

**Comment by dpino** [comment]
@kbara: +1

**Comment by aperezdc** [comment]
@kbara: That would be awesome! :smile:

**Comment by kbara** [comment]
... probably after redrawing them, since the Great Water Spill of yesterday left the more complex one a bit textured. :D

**Pull request merged**
