### PR TITLE
Move lwaftr/nexthop to snabbvmx/nexthop

### PR DESCRIPTION
**Pull request by dpino**
Since `nexthop` is a tool which only makes sense to use it together with snabbvmx, better to move it to snabbvmx folder.

### CODE REVIEW

**Comment by mwiget** [comment]
We could remove this completely, now that we can get the same info via snabb snabbvmx query and just parse the xml tag for the same info. This tiny program was useful when there was no simple way to access the shmem info.

**Comment by dpino** [comment]
SGTM. I would need to rework `snabbvmx/tests/nexthop/selftest.sh` to use `snabbvmx query` instead of `snabbvmx nexthop`, but I think is doable.

**Comment by mwiget** [comment]
Oh, in that case it does serve a purpose. I'm ok with leaving it alive ;-).

**Comment by dpino** [comment]
OK, I will leave it for now and create a new issue to replace it in the future.

I noticed the test was not running OK. This time the VM returns a next_hop_mac for IPv4 with the first 16-bit corrupted (before it only happened with the IPv6 MAC, it was pending to be solved).

```
PID '4085': next_hop_mac for IPv4 is 6a:34:99:99:99:99
PID '4085': next_hop_mac for IPv6 is 4f:12:99:99:99:99
```

I got the same values using `snabbvmx query`:

```
   <next_hop_mac_v4>6a:34:99:99:99:99</next_hop_mac_v4>
   <next_hop_mac_v6>4f:12:99:99:99:99</next_hop_mac_v6>
```

**Comment by mwiget** [comment]
Very strange. It always works fine for me using virtual interface and physical interfaces.

**Review by kbara — APPROVED** [review]
Approved, as there is a github issue about the corruption.

**Pull request merged**
