### PR TITLE
Added documentation of filter performance

### PR DESCRIPTION
**Pull request by kbara**

### CODE REVIEW

**Comment by wingo** [comment]
The other .md files use headings, i.e.

# Heading

## subheading

### etc

would you mind doing that?  Just for consistency.  The thing looks very nice but maybe consistent would be even better :)

**Comment by kbara** [comment]
Sure; I previously had headings and preferred them, but the docs I could find on github's markdown syntax didn't mention headings at all, and it uses a different syntax than the wiki I originally wrote this on.

**Comment by kbara** [comment]
Updated.

**Comment by wingo** [comment]
lgtm and thank you!  would you mind also preparing a backport to starfruit please?

**Comment by kbara** [comment]
I'll put the same document into starfruit, sure - the benchmarks were run against starfruit.

**Pull request merged**
