### PR TITLE
Migrate snabbvmx lwaftr to new configuration, more cleanups

### PR DESCRIPTION
**Pull request by wingo**

### CODE REVIEW

**Comment by wingo** [comment]
Oddly I'm seeing around 1-2% regression here relative to lwaftr for the bench workload.  I think it is acceptable for the moment tho; wdyt?

**Comment by kbara** [comment]
Performance regressions aren't blockers if we still hit line speed with out target packet mix, though they're not good.

**Comment by kbara** [comment]
LGTM

**Comment by mwiget** [comment]
Hmm, we are a bit sensitive when it comes to IMIX line rate performance at 0 packet loss. So with all the work that went it, it should improve, not decrease ...

**Comment by wingo** [comment]
What do you mean by your second sentence, Marcel?

**Comment by mwiget** [comment]
In relation to code optimizations done previously and the use of flush() etc. Not specific to the code at hand in this pull request. One of the goals of snabb has always been performance.

**Comment by wingo** [comment]
@mwiget understood :) I have been making these changes though with better configuration as a goal so I'm not actually trying right now to make things better on the perf front, just not make them worse.  We definitely care about not regressing!

**Comment by wingo** [comment]
Looking again it seems that something else was running on this machine while I was testing; I now see no regression AFAIU. Let's merge and tighten things up on `yang`.

**Comment by kbara** [comment]
@wingo Heads up on another branch. :-)

**Pull request merged**
