### PR TITLE
[RFC] Convert lwAFTR over to loops-and-queues style

### PR DESCRIPTION
**Pull request by wingo**
Instead of processing each packet one by one, this branch converts the lwAFTR to process packets in batches, moving each batch from queue to queue as the internal structure of the lwAFTR determines.

The idea here is that we should write code that plays to the strengths of LuaJIT, and LuaJIT's strength is tight and ideally branchless loops. In this style, we move packets from queue to queue.  Because the packets are alive in only a straight-line code path, LuaJIT's allocation sinking optimization does very well for this style of code.

Unfortunately this patch is currently a regression, relative to the upstream lwAFTR branch, so this is a work-in-progress patch set.

On `lwaftr` branch:

```
[wingo@snabb1:~/snabb/src]$ make && for i in `seq 4`; do sudo ./snabb lwaftr bench -D 5  --name test --cpu 2 program/lwaftr/tests/data/icmp_on_fail.conf program/lwaftr/tests/benchdata/ipv4-0550.pcap program/lwaftr/tests/benchdata/ipv6-0550.pcap; done
make: 'snabb' is up to date.
program/lwaftr/tests/data/icmp_on_fail.conf: loading compiled configuration from program/lwaftr/tests/data/icmp_on_fail.o
program/lwaftr/tests/data/icmp_on_fail.conf: compiled configuration is up to date.
Bound main process to NUMA node: 	0
Bound data plane to CPU:	2
Time (s),Decap. MPPS,Decap. Gbps,Encap. MPPS,Encap. Gbps
0.995835,2.468482,10.071408,2.468482,11.651236
1.995899,2.488640,10.153652,2.488640,11.746382
2.995941,2.488694,10.153871,2.488694,11.746635
3.995876,2.488963,10.154971,2.488963,11.747908
program/lwaftr/tests/data/icmp_on_fail.conf: loading compiled configuration from program/lwaftr/tests/data/icmp_on_fail.o
program/lwaftr/tests/data/icmp_on_fail.conf: compiled configuration is up to date.
Bound main process to NUMA node: 	0
Bound data plane to CPU:	2
Time (s),Decap. MPPS,Decap. Gbps,Encap. MPPS,Encap. Gbps
0.996330,3.071272,12.530791,3.071272,14.496405
1.996277,3.039761,12.402225,3.039761,14.347672
2.996215,3.029587,12.360714,3.029587,14.299650
3.996319,3.029085,12.358665,3.029085,14.297279
program/lwaftr/tests/data/icmp_on_fail.conf: loading compiled configuration from program/lwaftr/tests/data/icmp_on_fail.o
program/lwaftr/tests/data/icmp_on_fail.conf: compiled configuration is up to date.
Bound main process to NUMA node: 	0
Bound data plane to CPU:	2
Time (s),Decap. MPPS,Decap. Gbps,Encap. MPPS,Encap. Gbps
0.996449,3.040196,12.403999,3.040196,14.349724
1.996451,2.998793,12.235077,2.998793,14.154304
2.996535,2.998548,12.234076,2.998548,14.153147
3.996536,2.988596,12.193473,2.988596,14.106175
program/lwaftr/tests/data/icmp_on_fail.conf: loading compiled configuration from program/lwaftr/tests/data/icmp_on_fail.o
program/lwaftr/tests/data/icmp_on_fail.conf: compiled configuration is up to date.
Bound main process to NUMA node: 	0
Bound data plane to CPU:	2
Time (s),Decap. MPPS,Decap. Gbps,Encap. MPPS,Encap. Gbps
0.996521,3.019505,12.319579,3.019505,14.252062
1.996427,2.978679,12.153011,2.978679,14.059366
2.996479,2.978245,12.151239,2.978245,14.057315
3.996450,2.978487,12.152226,2.978487,14.058458
```

Then with this branch:

```
[wingo@snabb1:~/snabb/src]$ git checkout tight-loops-and-queues && make >/dev/null
[wingo@snabb1:~/snabb/src]$ make && for i in `seq 4`; do sudo ./snabb lwaftr bench -D 5  --name test --cpu 2 program/lwaftr/tests/data/icmp_on_fail.conf program/lwaftr/tests/benchdata/ipv4-0550.pcap program/lwaftr/tests/benchdata/ipv6-0550.pcap; done
make: 'snabb' is up to date.
program/lwaftr/tests/data/icmp_on_fail.conf: loading compiled configuration from program/lwaftr/tests/data/icmp_on_fail.o
program/lwaftr/tests/data/icmp_on_fail.conf: compiled configuration is up to date.
Bound main process to NUMA node: 	0
Bound data plane to CPU:	2
Time (s),Decap. MPPS,Decap. Gbps,Encap. MPPS,Encap. Gbps
0.996315,2.569669,10.484248,2.569669,12.128836
1.996273,2.590910,10.570912,2.590910,12.229095
2.996242,2.550079,10.404322,2.550079,12.036372
3.996266,2.580537,10.528592,2.580537,12.180136
program/lwaftr/tests/data/icmp_on_fail.conf: loading compiled configuration from program/lwaftr/tests/data/icmp_on_fail.o
program/lwaftr/tests/data/icmp_on_fail.conf: compiled configuration is up to date.
Bound main process to NUMA node: 	0
Bound data plane to CPU:	2
Time (s),Decap. MPPS,Decap. Gbps,Encap. MPPS,Encap. Gbps
0.996862,2.598954,10.603734,2.598954,12.267065
1.996779,2.621619,10.696205,2.631820,12.422189
2.996824,2.580484,10.528376,2.570285,12.131745
program/lwaftr/tests/data/icmp_on_fail.conf: loading compiled configuration from program/lwaftr/tests/data/icmp_on_fail.o
program/lwaftr/tests/data/icmp_on_fail.conf: compiled configuration is up to date.
Bound main process to NUMA node: 	0
Bound data plane to CPU:	2
Time (s),Decap. MPPS,Decap. Gbps,Encap. MPPS,Encap. Gbps
0.996817,2.588839,10.562465,2.588839,12.219322
1.996769,2.621527,10.695832,2.621527,12.373609
2.996802,2.570316,10.486888,2.570316,12.131890
3.996713,2.611432,10.654645,2.611432,12.325961
program/lwaftr/tests/data/icmp_on_fail.conf: loading compiled configuration from program/lwaftr/tests/data/icmp_on_fail.o
program/lwaftr/tests/data/icmp_on_fail.conf: compiled configuration is up to date.
Bound main process to NUMA node: 	0
Bound data plane to CPU:	2
Time (s),Decap. MPPS,Decap. Gbps,Encap. MPPS,Encap. Gbps
0.996591,2.538254,10.356076,2.538254,11.980559
1.996658,2.539628,10.361683,2.539628,11.987045
2.996629,2.539874,10.362687,2.539874,11.988207
3.996655,2.539734,10.362114,2.539734,11.987544
```

So, it seems like a losing strategy.  I don't know why :/

This branch in its beginning also includes the hacks proposed for #922.  Unfortunately, separate apps were also a slowdown!  I had to integrate this functionality inside the lwAFTR to regain perf and I still think I still lost a little bit (though not as much as shown above).  A bit of a disappointment :/

### CODE REVIEW

**Comment by wingo** [comment]
Perf on upstream `lwaftr` for small packets and setting `engine.pull_npackets` to 128 so that we evenly fill the lookup streamer:

```
[wingo@snabb1:~/snabb/src]$ make && sudo BURST_SIZE=128 ./snabb lwaftr bench -D 15  --name test --cpu 2 program/lwaftr/tests/data/icmp_on_fail.conf program/lwaftr/tests/benchdata/ipv{4,6}-0094.pcap
LUA       obj/program/lwaftr/setup_lua.o
GEN       obj/version.lua.gen
LUA       obj/version.lua
LINK      snabb
BINARY    3.5M snabb
pull_npackets	128
program/lwaftr/tests/data/icmp_on_fail.conf: loading compiled configuration from program/lwaftr/tests/data/icmp_on_fail.o
program/lwaftr/tests/data/icmp_on_fail.conf: compiled configuration is up to date.
Bound main process to NUMA node: 	0
pull_npackets	128
Bound data plane to CPU:	2
Time (s),Decap. MPPS,Decap. Gbps,Encap. MPPS,Encap. Gbps
0.996637,3.596095,1.553513,3.596095,3.855014
1.996500,3.520482,1.520848,3.520482,3.773957
2.996643,3.557891,1.537009,3.557891,3.814059
3.996602,3.532944,1.526232,3.532944,3.787316
4.996567,3.532925,1.526224,3.532925,3.787296
5.996499,3.571441,1.542863,3.571441,3.828585
6.996513,3.494352,1.509560,3.494352,3.745946
7.996549,3.596670,1.553762,3.596670,3.855631
traceprof report (recorded 9998/9998 samples):
 11% TRACE  15:LOOP          ->loop    
  8% TRACE  37:LOOP          ->loop    
  4% TRACE  56:LOOP          ->loop    
  3% TRACE  57:LOOP          ->loop    
  3% TRACE  53:LOOP          ->loop    
  3% TRACE  33:LOOP          ->loop    
  3% TRACE  21:LOOP          ->loop    
  2% TRACE  35:LOOP          ->loop    
  2% TRACE  19:LOOP          ->loop    
  2% TRACE  39:LOOP          ->loop    
  2% TRACE  60:LOOP          ->loop    
  2% TRACE  55:LOOP          ->loop    
  2% TRACE  32:LOOP          ->loop    
  2% TRACE  41:LOOP          ->loop    
  1% TRACE  49:LOOP          ->loop    
  1% TRACE  23:LOOP          ->loop    
  1% TRACE  20:LOOP          ->loop    
  1% TRACE  22:LOOP          ->loop    
  1% TRACE  73               ->55      
  1% TRACE  42:LOOP          ->loop    
  1% TRACE  59:LOOP          ->loop    
  1% TRACE  53               ->loop    
  1% TRACE  37               ->loop    
  1% TRACE  38:LOOP          ->loop    
8.996581,3.481486,1.504002,3.481486,3.732153
9.996497,3.622704,1.565008,3.622704,3.883539
10.996603,3.481234,1.503893,3.481234,3.731883
11.996568,3.622526,1.564931,3.622526,3.883348
12.996621,3.494216,1.509501,3.494216,3.745799
13.996549,3.597056,1.553928,3.597056,3.856044
```

I hacked that to enable traceprof in the worker process and to print out a summary after 10 seconds.  My interpretation is that most time is spent in loop bodies and only these lines indicate time spent in loop headers:

```
  1% TRACE  53               ->loop    
  1% TRACE  37               ->loop    
```

So if a benefit of this branch would be making LuaJIT spend more time in loop bodies and not headers, I think we're just not going to get that -- already very little time is spent outside loop bodies.  This traceprof run from this branch seems to bear that out:

```
[wingo@snabb1:~/snabb/src]$ make && sudo BURST_SIZE=128 ./snabb lwaftr bench -D 15  --name test --cpu 2 program/lwaftr/tests/data/icmp_on_fail.conf program/lwaftr/tests/benchdata/ipv{4,6}-0094.pcap
LUA       obj/apps/lwaftr/lwaftr_lua.o
GEN       obj/version.lua.gen
LUA       obj/version.lua
LINK      snabb
BINARY    3.5M snabb
pull_npackets	128
program/lwaftr/tests/data/icmp_on_fail.conf: loading compiled configuration from program/lwaftr/tests/data/icmp_on_fail.o
program/lwaftr/tests/data/icmp_on_fail.conf: compiled configuration is up to date.
Bound main process to NUMA node: 	0
pull_npackets	128
Bound data plane to CPU:	2
Time (s),Decap. MPPS,Decap. Gbps,Encap. MPPS,Encap. Gbps
0.996426,3.108711,1.342963,3.108711,3.332538
1.996405,3.123264,1.349250,3.123264,3.348139
2.996368,3.008111,1.299504,3.008111,3.224695
3.996379,3.097568,1.338149,3.097568,3.320593
4.996491,3.122848,1.349070,3.122848,3.347693
5.996378,3.033943,1.310663,3.033943,3.252387
6.996375,3.072011,1.327109,3.072011,3.293196
7.996522,3.109941,1.343494,3.109941,3.333856
traceprof report (recorded 9999/9999 samples):
  9% TRACE  11:LOOP          ->loop    
  6% TRACE  35:LOOP          ->loop    
  4% TRACE  42:LOOP          ->loop    
  3% TRACE  51:LOOP          ->loop    
  3% TRACE  33:LOOP          ->loop    
  2% TRACE  49:LOOP          ->loop    
  2% TRACE  32:LOOP          ->loop    
  2% TRACE  52:LOOP          ->loop    
  2% TRACE  18:LOOP          ->loop    
  2% TRACE  54:LOOP          ->loop    
  2% TRACE  56:LOOP          ->loop    
  2% TRACE  44:LOOP          ->loop    
  2% TRACE  37:LOOP          ->loop    
  2% TRACE  30:LOOP          ->loop    
  2% TRACE  48:LOOP          ->loop    
  1% TRACE  36:LOOP          ->loop    
  1% TRACE  20:LOOP          ->loop    
  1% TRACE  38:LOOP          ->loop    
  1% TRACE  40:LOOP          ->loop    
  1% TRACE  16:LOOP          ->loop    
  1% TRACE  46:LOOP          ->loop    
  1% TRACE  23:LOOP          ->loop    
  1% TRACE  19:LOOP          ->loop    
  1% TRACE  39:LOOP          ->loop    
  1% TRACE  31:LOOP          ->loop    
  1% TRACE  53:LOOP          ->loop    
8.996501,3.059265,1.321602,3.059265,3.279532
9.996366,3.046810,1.316222,3.046810,3.266181
10.996422,3.110227,1.343618,3.110227,3.334164
11.996366,3.097774,1.338238,3.097774,3.320814
^C
```

So all the time is in loops: great, I guess; yet, it is slower.  Could it be that having smaller loops means more loop overhead, and actually we should be looking to increase loop size?  You wouldn't think that... but maybe???

**Comment by wingo** [comment]
Or, is this test workload pathologically simple?  It's all traffic that doesn't need hairpinning, doesn't include ICMP traffic, and is always matching the binding table.

**Comment by lukego** [comment]
> Or, is this test workload pathologically simple?

_Could be_ that the many smaller loops provide more robustness. If the workload were more complex then you may be exercising more side traces, due to more guards failing and exits being taken, and this may be more disruptive if you have one big loop (one failing guard is a spanner in the works for all processing of that packet.)

**Comment by wingo** [comment]
Yeah there is just no way this is going to work.  Testing against traffic on our lab machines instead of with the synthetic tester, the current code can do 2.49+2.49 MPPS FDX on a core (two-interface configuration) without dropping on small packets, whereas this branch can only do 2.235+2.235.

**Comment by wingo** [comment]
I rebased this one on top of current `lwaftr` and force-pushed it.  I was wondering if my previous tests were using a degenerate workload -- like single packets or something.  So I gave it a go with a 1e6-entry binding table with 2e4 active softwires on our servers.  Sadly I reproduce the same results -- this PR can't handle as much traffic as `lwaftr`.  As an example, here was what `lwaftr` did at 10 Gbps, bump-in-the-wire:

```
Applying 10.000000 Gbps of load.
  v4:
    TX 4251234 packets (2.125617 MPPS), 2397695976 bytes (9.998902 Gbps)
    RX 3983994 packets (1.991997 MPPS), 2406332376 bytes (10.007793 Gbps)
    Loss: 0 ingress drop + 267240 packets lost (6.286175%)
  v6:
    TX 3980649 packets (1.990325 MPPS), 2404311996 bytes (9.999390 Gbps)
    RX 3979002 packets (1.989501 MPPS), 2244157128 bytes (9.358613 Gbps)
    Loss: 0 ingress drop + 1647 packets lost (0.041375%)
```

Compared to this PR:

```
Applying 10.000000 Gbps of load.
  v4:
    TX 4251647 packets (2.125824 MPPS), 2397928908 bytes (9.999874 Gbps)
    RX 3594920 packets (1.797460 MPPS), 2171331680 bytes (9.030439 Gbps)
    Loss: 0 ingress drop + 656727 packets lost (15.446414%)
  v6:
    TX 3980841 packets (1.990420 MPPS), 2404427964 bytes (9.999873 Gbps)
    RX 3594880 packets (1.797440 MPPS), 2027512320 bytes (8.455158 Gbps)
    Loss: 0 ingress drop + 385961 packets lost (9.695464%)
```

**Comment by eugeneia** [comment]
Some comments from someone who has been down that route: I believe the general hypothesis to hold true, but  testing this led me to believe me there is a fixpoint where the cost of one more loop outweighs the cost of a branch. More interestingly, I recently removed all the “synthetic” loops and instead split up the app in question into smaller apps. The result was basically the same thing, except “many small loops” arose naturally from the app hierarchy instead of being coded manually case-by-case. (Performance was unchanged.)

So my take would be to avoid things like this branch’s “ilink” and think about larger app networks with smaller apps instead. I suppose Snabb aligns itself naturally with the JIT, but it took me a while to fully embrace the app as a unit of code sized between module and function. As a reference of scale: I have an app that just adds a header to the packet, and three different apps that just dispatch to different output links based on some matching on headers. So `if then else` might become an app with ports `if => {then, else}`.

**Comment by eugeneia** [comment]
I think of it a bit as an [SPMD](https://en.wikipedia.org/wiki/SPMD) architecture. Maybe Snabb is a bit like [Volta](http://pharr.org/matt/blog/2018/04/26/ispc-volta-more-on-performance.html) in this regard, only instead of execution masks we have links.

**Comment by wingo** [comment]
Closing as I have no plan to work on this.

**Pull request closed without merging**
